@startuml
'https://plantuml.com/class-diagram


class Student {

-studentName :String
-studentGrade :char
-studentGroup :int
-secretNickName :String
-studentGradeArray :char[]
-studentGroupArray :int[]
+Student(studentName :String,studentGrade :char,studentGroup :int):void
+getStudentName():String
+getStudentGrade():char
+gradeUpgrade():void
+gradeDowngrade():void

}



@enduml